2023-09-23 18:48:49,457 INFO    MainThread:3946 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-09-23 18:48:49,457 INFO    MainThread:3946 [wandb_setup.py:_flush():76] Configure stats pid to 3946
2023-09-23 18:48:49,457 INFO    MainThread:3946 [wandb_setup.py:_flush():76] Loading settings from /Users/irshad/.config/wandb/settings
2023-09-23 18:48:49,457 INFO    MainThread:3946 [wandb_setup.py:_flush():76] Loading settings from /Users/irshad/Dev/PyEnv/GTM-Transformer/wandb/settings
2023-09-23 18:48:49,458 INFO    MainThread:3946 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-23 18:48:49,458 INFO    MainThread:3946 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-23 18:48:49,458 INFO    MainThread:3946 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'train.py'}
2023-09-23 18:48:49,458 INFO    MainThread:3946 [wandb_init.py:_log_setup():524] Logging user logs to /Users/irshad/Dev/PyEnv/GTM-Transformer/wandb/run-20230923_184849-g40tfwnu/logs/debug.log
2023-09-23 18:48:49,458 INFO    MainThread:3946 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/irshad/Dev/PyEnv/GTM-Transformer/wandb/run-20230923_184849-g40tfwnu/logs/debug-internal.log
2023-09-23 18:48:49,458 INFO    MainThread:3946 [wandb_init.py:init():564] calling init triggers
2023-09-23 18:48:49,458 INFO    MainThread:3946 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-09-23 18:48:49,458 INFO    MainThread:3946 [wandb_init.py:init():614] starting backend
2023-09-23 18:48:49,458 INFO    MainThread:3946 [wandb_init.py:init():618] setting up manager
2023-09-23 18:48:49,465 INFO    MainThread:3946 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-09-23 18:48:49,468 INFO    MainThread:3946 [wandb_init.py:init():624] backend started and connected
2023-09-23 18:48:49,485 INFO    MainThread:3946 [wandb_init.py:init():715] updated telemetry
2023-09-23 18:48:49,514 INFO    MainThread:3946 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2023-09-23 18:48:50,168 ERROR   MainThread:3946 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-23 18:48:50,443 ERROR   MainThread:3946 [wandb_init.py:init():1183] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/irshad/Dev/PyEnv/env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/Users/irshad/Dev/PyEnv/env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-23 18:48:51,908 WARNING MsgRouterThr:3946 [router.py:message_loop():77] message_loop has been closed
